name: Move closed issues into Konsyuyattakoto

on:
  issues:
    types: [closed]

jobs:
  automate-project-columns:
    runs-on: ubuntu-latest
    steps:
      - uses: alex-page/github-project-automation-plus@v0.8.1
        with:
          project: 開発
          column: 今週やったこと
          repo-token: ${{ secrets.GHPROJECT_TOKEN }}
